# Generated by Django 5.2 on 2025-05-22 07:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_user', '0003_userprofile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='mobile number'),
        ),
    ]
