# Generated by Django 5.2 on 2025-05-26 13:06

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_user', '0004_alter_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='django-backend-dev-private'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='resume'),
        ),
    ]
