# Generated by Django 5.2 on 2025-07-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_user', '0007_cashfreeorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashfreeOrder',
        ),
    ]
