# Generated by Django 5.2 on 2025-05-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='catagory',
            new_name='category',
        ),
    ]
