
services:
  db:
    image: mysql:8.4.5
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE='Quick_edu_user'
      - MYSQL_ROOT_PASSWORD='root'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db


